package com.weiqiaoshiyan.student.manager.entity;

public class sysTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.id
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.name
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.nodeId
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.pid
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.type
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.url
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.icon
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysTree.level
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.id
     *
     * @return the value of sysTree.id
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.id
     *
     * @param id the value for sysTree.id
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.name
     *
     * @return the value of sysTree.name
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.name
     *
     * @param name the value for sysTree.name
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.nodeId
     *
     * @return the value of sysTree.nodeId
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.nodeId
     *
     * @param nodeId the value for sysTree.nodeId
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.pid
     *
     * @return the value of sysTree.pid
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.pid
     *
     * @param pid the value for sysTree.pid
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.type
     *
     * @return the value of sysTree.type
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.type
     *
     * @param type the value for sysTree.type
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.url
     *
     * @return the value of sysTree.url
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.url
     *
     * @param url the value for sysTree.url
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.icon
     *
     * @return the value of sysTree.icon
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.icon
     *
     * @param icon the value for sysTree.icon
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysTree.level
     *
     * @return the value of sysTree.level
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysTree.level
     *
     * @param level the value for sysTree.level
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}