package com.weiqiaoshiyan.student.manager.mapper;

import com.weiqiaoshiyan.student.manager.entity.sysTree;
import com.weiqiaoshiyan.student.manager.entity.sysTreeExample;
import java.util.List;

import com.weiqiaoshiyan.student.manager.sqlProvider.sysTreeSqlProvider;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface sysTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @SelectProvider(type=sysTreeSqlProvider.class, method="countByExample")
    long countByExample(sysTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @DeleteProvider(type=sysTreeSqlProvider.class, method="deleteByExample")
    int deleteByExample(sysTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @Delete({
        "delete from sysTree",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @Insert({
        "insert into sysTree (id, name, ",
        "nodeId, pid, type, ",
        "url, icon, level)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{nodeId,jdbcType=VARCHAR}, #{pid,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{url,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR}, #{level,jdbcType=INTEGER})"
    })
    int insert(sysTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @InsertProvider(type=sysTreeSqlProvider.class, method="insertSelective")
    int insertSelective(sysTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @SelectProvider(type=sysTreeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="nodeId", property="nodeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER)
    })
    List<sysTree> selectByExample(sysTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @Select({
        "select",
        "id, name, nodeId, pid, type, url, icon, level",
        "from sysTree",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="nodeId", property="nodeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER)
    })
    sysTree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @UpdateProvider(type=sysTreeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") sysTree record, @Param("example") sysTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @UpdateProvider(type=sysTreeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") sysTree record, @Param("example") sysTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @UpdateProvider(type=sysTreeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(sysTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysTree
     *
     * @mbg.generated Tue Jul 30 01:16:23 CST 2019
     */
    @Update({
        "update sysTree",
        "set name = #{name,jdbcType=VARCHAR},",
          "nodeId = #{nodeId,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "url = #{url,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(sysTree record);
}